---
title: "Jack Bailey"
author: |
  | jack.bailey@manchester.ac.uk
  | +44 (0)7446 875623
indent: no
fontsize: 12pt
geometry: margin = 1.15in
subparagraph: yes
compact-title: false
classoption: a4paper
output: 
  bookdown::pdf_document2: 
    latex_engine: xelatex
    toc: false
    keep_tex: false
    includes:
      in_header:
        - _assets/rmd-preamble.tex
    number_sections: false
---

# Appointments

\begin{minipage}[t]{\linewidth}
\textbf{Lecturer in Quantitative Politics} \hfill 2023--Present\\
\emph{The University of Manchester}\\
\end{minipage}

\begin{minipage}[t]{\linewidth}
\textbf{Research Associate on the British Election Study} \hfill 2020--2023\\
\emph{The University of Manchester}\\
\end{minipage}

\begin{minipage}[t]{\linewidth}
\textbf{Visiting Fellow} \hfill Sept--Dec 2019\\
\emph{The University of Texas at Austin}
\end{minipage}


# Education

\begin{minipage}[t]{\linewidth}
\textbf{PhD Politics} \hfill 2017--2022\\
\emph{The University of Manchester}\\
\end{minipage}

\begin{minipage}[t]{\linewidth}
\textbf{PGDip Social Research Methods and Statistics} \hfill 2016--2017\\
\emph{The University of Manchester}\\
\end{minipage}

\begin{minipage}[t]{\linewidth}
\textbf{MA Politics} \hfill 2011--2012 \\
\emph{The University of Sheffield}\\
\end{minipage}

\begin{minipage}[t]{\linewidth}
\textbf{BA (Hons.) Business Management} \hfill 2008--2011 \\
\emph{The University of Sheffield}
\end{minipage}


# Book Projects

\begin{minipage}[t]{\linewidth}
Fieldhouse, E.; Green, J.; Evans. G.; Mellon, J.; Prosser, C.; and Bailey, J. (2024). \emph{Electoral Realignment}. Under contract at Oxford University Press\\
\end{minipage}

# Peer Reviewed Publications

\begin{minipage}[t]{\linewidth}
Fieldhouse, E. and Bailey, J. (2023). A New Electoral Map? Brexit, Realignment and the Changing Geography of Party Support in England. \emph{Political Geography}.\\
\end{minipage}

\begin{minipage}[t]{\linewidth}
Bailey, J. (2021). Political Surveys Bias Self-Reported Economic Perceptions. \emph{Public Opinion Quarterly}. Available at: https://doi.org/10.33774/apsa-2021-13lpq.\\
\end{minipage}

\begin{minipage}[t]{\linewidth}
Mellon, J.; Bailey, J. \& Prosser, C. (2021). How Do Coronavirus Attitudes Fit into Britain's Ideological Landscape? \emph{Parliamentary Affairs}. Available at: https://doi.org/10.1093/pa/gsab030.\\
\end{minipage}

\begin{minipage}[t]{\linewidth}
Fieldhouse, E.; Cutts, D. \& Bailey, J. (2020). Who cares if you vote? Partisan pressure and social norms of voting. \emph{Political Behavior}. Available at: https://doi.org/10.1007/s11109-020-09661-y.\\
\end{minipage}

\begin{minipage}[t]{\linewidth}
Bailey, J. (2019). The fact remains: Party ID moderates how voters respond to economic change. \emph{Electoral Studies}, 61(102071). Available at: https://doi.org/10.1016/j.electstud.2019.102071.\\
\end{minipage}

# Manuscripts Under Review

<!-- \begin{minipage}[t]{\linewidth} -->
<!-- Bailey, J.; Pack, M.; and Mansillo, L. PollBasePro: Daily Estimates of Aggregate Voting Intention in Britain from 1955 to the Present Day. Under review at \emph{Electoral Studies}. Available at: https://doi.org/10.33774/apsa-2021-2hbgw-v2\\ -->
<!-- \end{minipage} -->

\begin{minipage}[t]{\linewidth}
Bailey, J. Common Retrospective Economic Perception Items Show Good Test-Retest Reliability. Under review at \emph{The Journal of Elections, Public Opinion, and Parties}. Under review at \emph{Research \& Politics}. Available at: https://doi.org/10.33774/apsa-2022-nhhsv-v2\\
\end{minipage}

# Working Papers

\begin{minipage}[t]{\linewidth}
Mellon, J., Bailey, J., Scott, R., Breckwoldt, J., \& Miori, M. Do LLMs know what the Most Important Issue is? Using Large Language Models to Code Open-Text Social Survey Responses At Scale. Available at: https://ssrn.com/abstract=4310154\\
\end{minipage}

\begin{minipage}[t]{\linewidth}
Fieldhouse, E., Bailey, J., \& Prosser, C. Campaign Slogans, Political Identities, and Emotional Responses.
\end{minipage}

\begin{minipage}[t]{\linewidth}
Bailey, J. What's the Half-Life of the Economic Vote? (About a Year and a Half). Available at: https://doi.org/10.33774/apsa-2021-kdrwl-v3\\
\end{minipage}

<!-- \begin{minipage}[t]{\linewidth} -->
<!-- Bailey, J.; Sanders, A.; Barclay, A. \& McDonnell A. Voting at the Intersection of Sexuality and Gender.\\ -->
<!-- \end{minipage} -->

# Funding and Awards

* UoM Faculty of Humanities Award for Distinguished Achievement (£100) \hfill 2021
* NWSSDTP/ESRC Overseas Institutional Visit Funding (£4,000) \hfill 2019
* Leuven-Montréal Winter School, Best Paper (€500) \hfill 2019
* PSA ECN Conference, Best Paper \hfill 2018
* YouGov, Survey Funding (£60,000) \hfill 2017--2020
* YouGov, Travel and Accommodation Research Funding (£5,000) \hfill 2017--2020
* ESRC, Data Science Stipend (£9,000) \hfill 2017--2020
* ESRC, CASE Studentship (£58,494) \hfill 2017--2020


# Select Conference Papers and Invited Presentations

\begin{minipage}[t]{\linewidth}
\textbf{What's the Half-Life of the Economic Vote? (About a Year and a Half)} \hfill Mar. 2023 \\
\emph{DPIR Politics Colloquium, Oxford University}\\
\end{minipage}

\begin{minipage}[t]{\linewidth}
\textbf{What's the Half-Life of the Economic Vote? (About a Year and a Half)} \hfill Apr. 2021 \\
\emph{Midwest Political Science Assocation Conference, 2021}\\
\end{minipage}

\begin{minipage}[t]{\linewidth}
\textbf{What's the Half-Life of the Economic Vote? (About a Year and a Half)} \hfill Oct. 2020 \\
\emph{Political Behaviour Colloquium, European University Institute}\\
\end{minipage}

\begin{minipage}[t]{\linewidth}
\textbf{Voting at the Intersection of Sexuality and Gender} \hfill Oct. 2020 \\
\emph{Queer Politics at Princeton, Princeton University}\\
\end{minipage}

\begin{minipage}[t]{\linewidth}
\textbf{Causal Inference for Ordinal Outcome Variables} \hfill 2020 \\
\emph{PSA Political Methodology Conference}\\
\end{minipage}

\begin{minipage}[t]{\linewidth}
\textbf{The Behaviour of Gay, Lesbian, and Bisexual Voters in Britain} \hfill 2019 \\
\emph{American Political Science Association Conference}\\
\end{minipage}

\begin{minipage}[t]{\linewidth}
\textbf{The Behaviour of Gay, Lesbian, and Bisexual Voters in Britain} \hfill 2019 \\
\emph{Political Studies Association Conference}\\
\end{minipage}

\begin{minipage}[t]{\linewidth}
\textbf{Imperfect Perceptions: How Latent Confounding Explains the Economic Vote} \hfill 2019 \\
\emph{Leuven-Montréal Winter School on Elections}\\
\end{minipage}

\begin{minipage}[t]{\linewidth}
\textbf{Party ID Moderates How Voters Respond to Economic Change} \hfill 2019 \\
\emph{Political Studies Association Conference}\\
\end{minipage}

\begin{minipage}[t]{\linewidth}
\textbf{Structural Equation Modelling for Political Research} \hfill 2018 \\
\emph{PSA Political Psychology Conference}\\
\end{minipage}

\begin{minipage}[t]{\linewidth}
\textbf{Competing Competence: A New Model of the Economic Vote} \hfill 2018 \\
\emph{Elections, Public Opinion, and Parties Conference}\\
\end{minipage}

<!-- \begin{minipage}[t]{\linewidth} -->
<!-- \textbf{Affective Asymmetry: Party ID Moderates Voters’ Responsiveness to Economic Change} \hfill 2018 \\ -->
<!-- \emph{Political Studies Association Early Careers Network Conference} -->
<!-- \end{minipage} -->


# Teaching

* Understanding Political Change (Lecturer) \hfill 2021--Present
* Introduction to Data Analysis 1 (Lecturer) \hfill 2019
* Introduction to Data Analysis 2 (Lecturer) \hfill 2019
* Structural Equation Modelling using MPlus (Teaching Assistant) \hfill 2019
* Making Sense of Politics (Teaching Assistant) \hfill 2017--2019
* Researching Culture and Society (Teaching Assistant) \hfill 2018
* Longitudinal Data Analysis (Teaching Assistant) \hfill 2018
* Introduction to Longitudinal Data Analysis (Teaching Assistant) \hfill 2018
* Introduction to R (Teaching Assistant) \hfill 2017


# Methods Training

* Bayesian Methods, University of Lancaster \hfill 2018
* Methods for Missing Data, University of Lancaster \hfill 2018
* Longitudinal Data Analysis, University of Manchester \hfill 2017
* Multilevel Modelling, University of Manchester \hfill 2017
* Structural Equation Modelling, University of Manchester \hfill 2017
* Social Network Analysis, University of Manchester \hfill 2017
* Survey Methods, University of Manchester \hfill 2016


# Additional Skills, Experience, and Service

* Key skills include statistical analysis, the R programming language, the Stan probabilistic programming language, the Stata and SPSS statistical software packages, longitudinal and panel data, structural equation and latent variable modelling, experiments and causal inference, and Bayesian statistics
* Experience organising events including a small conference on the 2017 UK general election and numerous large-scale public lectures and events
* Four years experience at LSE and Cardiff University on knowledge exchange projects
* American Political Science Association and Political Studies Association member
* Reviewer for *The American Political Science Review*, *The International Journal of Forecasting*, and *Electoral Studies*


# References

\begin{minipage}[t]{0.45\linewidth}
\textbf{Prof. Edward Fieldhouse}\\
Professor of Social and Political Science,\\
University of Manchester\\
\emph{ed.fieldhouse@manchester.ac.uk}
\end{minipage}
\hfill
\begin{minipage}[t]{0.45\linewidth}
\textbf{Dr. Jonathan Mellon}\\
Assistant Professor,\\
US Military Academy West Point\\
\emph{jonathan.mellon@westpoint.edu}
\end{minipage}

\vspace{.5cm}

\begin{minipage}[t]{0.45\linewidth}
\textbf{Prof. Geoffrey Evans}\\
Professor of the Sociology of Politics,\\
The University of Oxford\\
\emph{geoffrey.evans@nuffield.ox.ac.uk}
\end{minipage}
\hfill
\begin{minipage}[t]{0.45\linewidth}
\textbf{Prof. Jane Green}\\
Professor of Political Science,\\
The University of Oxford\\
\emph{jane.green@nuffield.ox.ac.uk}
\end{minipage}